# Auto-generated by ukg-to-entra on 2026-06-04 10:20
# Apply these changes on a domain-joined machine with RSAT/AD module.
# 153 AD-synced user(s) whose HR data must be set in on-prem AD.
#
# AD attribute mapping:
#   jobTitle         -> title
#   department       -> department
#   officeLocation   -> physicalDeliveryOfficeName (Office)
#   manager          -> manager (DN reference, resolved by UPN)
#
# REVIEW this script before running. Dry-run with -WhatIf is recommended.

Import-Module ActiveDirectory

# --- User: Molly Macmath (director@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'director@compassrapecrisis.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Molly Macmath"
    }
} else {
    Write-Warning "User director@compassrapecrisis.org not found in AD"
}

# --- User: Carole Hershey (chershey@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'chershey@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jennifer Fire <jfire@goodwillgoodskills.org> (UPN: jfire@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jfire@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jfire@goodwillgoodskills.org) for Carole Hershey"
    }
} else {
    Write-Warning "User chershey@goodwillgoodskills.org not found in AD"
}

# --- User: Philip Romano (promano@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'promano@goodwillgoodskills.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Philip Romano"
    }
} else {
    Write-Warning "User promano@goodwillgoodskills.org not found in AD"
}

# --- User: Nancy O'Donnell (nodonnell@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'nodonnell@goodwillgoodskills.org'"
if ($user) {
    # Manager: Averie Destefano <adestefano@goodwillgoodskills.org> (UPN: adestefano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'adestefano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN adestefano@goodwillgoodskills.org) for Nancy O'Donnell"
    }
} else {
    Write-Warning "User nodonnell@goodwillgoodskills.org not found in AD"
}

# --- User: Brandon Clow (bclow@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
if ($user) {
    # Manager: Phil Romano <promano@goodwillgoodskills.org> (UPN: promano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'promano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN promano@goodwillgoodskills.org) for Brandon Clow"
    }
} else {
    Write-Warning "User bclow@goodwillgoodskills.org not found in AD"
}

# --- User: Linda Uehlein (luehlein@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'luehlein@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Linda Uehlein"
    }
} else {
    Write-Warning "User luehlein@goodwillgoodskills.org not found in AD"
}

# --- User: Jessica Canterbury (jcanterbury@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jcanterbury@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Jessica Canterbury"
    }
} else {
    Write-Warning "User jcanterbury@goodwillgoodskills.org not found in AD"
}

# --- User: Ellen McCarthy (emccarthy@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'emccarthy@goodwillgoodskills.org'"
if ($user) {
    # Manager: Anne Richards <annerichards@goodwillgoodskills.org> (UPN: annerichards@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'annerichards@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN annerichards@goodwillgoodskills.org) for Ellen McCarthy"
    }
} else {
    Write-Warning "User emccarthy@goodwillgoodskills.org not found in AD"
}

# --- User: Cheryl Musgrove (CMusgrove@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'CMusgrove@goodwillgoodskills.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Cheryl Musgrove"
    }
} else {
    Write-Warning "User CMusgrove@goodwillgoodskills.org not found in AD"
}

# --- User: Amy Humrighouse (ahumrighouse@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ahumrighouse@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jennifer Fire <jfire@goodwillgoodskills.org> (UPN: jfire@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jfire@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jfire@goodwillgoodskills.org) for Amy Humrighouse"
    }
} else {
    Write-Warning "User ahumrighouse@goodwillgoodskills.org not found in AD"
}

# --- User: Debra Seabolt (dseabolt@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dseabolt@goodwillgoodskills.org'"
if ($user) {
    # Manager: Averie Destefano <adestefano@goodwillgoodskills.org> (UPN: adestefano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'adestefano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN adestefano@goodwillgoodskills.org) for Debra Seabolt"
    }
} else {
    Write-Warning "User dseabolt@goodwillgoodskills.org not found in AD"
}

# --- User: Jennifer Fire (jfire@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jfire@goodwillgoodskills.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Jennifer Fire"
    }
} else {
    Write-Warning "User jfire@goodwillgoodskills.org not found in AD"
}

# --- User: Kara Bhakuni (kbhakuni@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kbhakuni@goodwillgoodskills.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Kara Bhakuni"
    }
} else {
    Write-Warning "User kbhakuni@goodwillgoodskills.org not found in AD"
}

# --- User: Susan Gardner (sgardner@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'sgardner@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Susan Gardner"
    }
} else {
    Write-Warning "User sgardner@goodwillgoodskills.org not found in AD"
}

# --- User: Michael Murphy (mmurphy@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mmurphy@goodwillgoodskills.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Michael Murphy"
    }
} else {
    Write-Warning "User mmurphy@goodwillgoodskills.org not found in AD"
}

# --- User: Krystle Snider (ksnider@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ksnider@goodwillgoodskills.org'"
if ($user) {
    # Manager: Nolberto Giraldo <ngiraldo@goodwillgoodskills.org> (UPN: ngiraldo@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'ngiraldo@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN ngiraldo@goodwillgoodskills.org) for Krystle Snider"
    }
} else {
    Write-Warning "User ksnider@goodwillgoodskills.org not found in AD"
}

# --- User: David Schollaert (dschollaert@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dschollaert@goodwillgoodskills.org'"
if ($user) {
    # Manager: Phil Romano <promano@goodwillgoodskills.org> (UPN: promano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'promano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN promano@goodwillgoodskills.org) for David Schollaert"
    }
} else {
    Write-Warning "User dschollaert@goodwillgoodskills.org not found in AD"
}

# --- User: Taryn Schneff (tschneff@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'tschneff@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Taryn Schneff"
    }
} else {
    Write-Warning "User tschneff@goodwillgoodskills.org not found in AD"
}

# --- User: Denise Kirven (greeter2@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'greeter2@goodwillgoodskills.org'"
if ($user) {
    # Manager: Colleen Porter <cporter@goodwillgoodskills.org> (UPN: cporter@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cporter@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cporter@goodwillgoodskills.org) for Denise Kirven"
    }
} else {
    Write-Warning "User greeter2@goodwillgoodskills.org not found in AD"
}

# --- User: Cynthia Woodall (cwoodall@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Cynthia Woodall"
    }
} else {
    Write-Warning "User cwoodall@goodwillgoodskills.org not found in AD"
}

# --- User: Crystal Page (cpage@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cpage@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Crystal Page"
    }
} else {
    Write-Warning "User cpage@goodwillgoodskills.org not found in AD"
}

# --- User: Leslie Bendter (lbendter@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'lbendter@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Leslie Bendter"
    }
} else {
    Write-Warning "User lbendter@goodwillgoodskills.org not found in AD"
}

# --- User: Vincenzo Di Pio (vdipio@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'vdipio@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Vincenzo Di Pio"
    }
} else {
    Write-Warning "User vdipio@goodwillgoodskills.org not found in AD"
}

# --- User: Megan Clow (mclow@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Megan Clow"
    }
} else {
    Write-Warning "User mclow@goodwillgoodskills.org not found in AD"
}

# --- User: Gay Norris (gnorris@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'gnorris@goodwillgoodskills.org'"
if ($user) {
    # Manager: Colleen Porter <cporter@goodwillgoodskills.org> (UPN: cporter@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cporter@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cporter@goodwillgoodskills.org) for Gay Norris"
    }
} else {
    Write-Warning "User gnorris@goodwillgoodskills.org not found in AD"
}

# --- User: Amanda Gauze (agauze@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Amanda Gauze"
    }
} else {
    Write-Warning "User agauze@goodwillgoodskills.org not found in AD"
}

# --- User: Trish Dawson (tdawson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'tdawson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Marcie Finney <mfinney@goodwillgoodskills.org> (UPN: mfinney@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mfinney@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mfinney@goodwillgoodskills.org) for Trish Dawson"
    }
} else {
    Write-Warning "User tdawson@goodwillgoodskills.org not found in AD"
}

# --- User: Jason Beamish (jbeamish@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jbeamish@goodwillgoodskills.org'"
if ($user) {
    # Manager: Phil Romano <promano@goodwillgoodskills.org> (UPN: promano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'promano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN promano@goodwillgoodskills.org) for Jason Beamish"
    }
} else {
    Write-Warning "User jbeamish@goodwillgoodskills.org not found in AD"
}

# --- User: Stacie Ady (sshackle@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'sshackle@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Stacie Ady"
    }
} else {
    Write-Warning "User sshackle@goodwillgoodskills.org not found in AD"
}

# --- User: Christian Williams (cwilliams@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cwilliams@goodwillgoodskills.org'"
if ($user) {
    # Manager: Michael Murphy <mmurphy@goodwillgoodskills.org> (UPN: mmurphy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mmurphy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mmurphy@goodwillgoodskills.org) for Christian Williams"
    }
} else {
    Write-Warning "User cwilliams@goodwillgoodskills.org not found in AD"
}

# --- User: Averie Destefano (adestefano@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'adestefano@goodwillgoodskills.org'"
if ($user) {
    # Manager: Mark Trew <mtrew@goodwillgoodskills.org> (UPN: mtrew@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mtrew@goodwillgoodskills.org) for Averie Destefano"
    }
} else {
    Write-Warning "User adestefano@goodwillgoodskills.org not found in AD"
}

# --- User: Christopher Ady (cady@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cady@goodwillgoodskills.org'"
if ($user) {
    # Manager: Ellen McCarthy <emccarthy@goodwillgoodskills.org> (UPN: emccarthy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'emccarthy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN emccarthy@goodwillgoodskills.org) for Christopher Ady"
    }
} else {
    Write-Warning "User cady@goodwillgoodskills.org not found in AD"
}

# --- User: Vicki Mowery (vmowery@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'vmowery@goodwillgoodskills.org'"
if ($user) {
    # Manager: Trish Dawson <tdawson@goodwillgoodskills.org> (UPN: tdawson@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'tdawson@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN tdawson@goodwillgoodskills.org) for Vicki Mowery"
    }
} else {
    Write-Warning "User vmowery@goodwillgoodskills.org not found in AD"
}

# --- User: Cynthia Thiessen (cthiessen@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cthiessen@goodwillgoodskills.org'"
if ($user) {
    # Manager: Michael Murphy <mmurphy@goodwillgoodskills.org> (UPN: mmurphy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mmurphy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mmurphy@goodwillgoodskills.org) for Cynthia Thiessen"
    }
} else {
    Write-Warning "User cthiessen@goodwillgoodskills.org not found in AD"
}

# --- User: Meghan Freyburger (mfreyburger@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mfreyburger@goodwillgoodskills.org'"
if ($user) {
    # Manager: Kevin Akans <kakans@goodwillgoodskills.org> (UPN: kakans@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'kakans@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN kakans@goodwillgoodskills.org) for Meghan Freyburger"
    }
} else {
    Write-Warning "User mfreyburger@goodwillgoodskills.org not found in AD"
}

# --- User: Jill Zarrelli (jzarrelli@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jzarrelli@goodwillgoodskills.org'"
if ($user) {
    # Manager: Kevin Akans <kakans@goodwillgoodskills.org> (UPN: kakans@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'kakans@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN kakans@goodwillgoodskills.org) for Jill Zarrelli"
    }
} else {
    Write-Warning "User jzarrelli@goodwillgoodskills.org not found in AD"
}

# --- User: Jennifer Hurst (jhurst@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jhurst@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Jennifer Hurst"
    }
} else {
    Write-Warning "User jhurst@goodwillgoodskills.org not found in AD"
}

# --- User: Jami George (jgeorge@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
if ($user) {
    # Manager: Phil Romano <promano@goodwillgoodskills.org> (UPN: promano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'promano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN promano@goodwillgoodskills.org) for Jami George"
    }
} else {
    Write-Warning "User jgeorge@goodwillgoodskills.org not found in AD"
}

# --- User: Robert Johnson (rjohnson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'rjohnson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Averie Destefano <adestefano@goodwillgoodskills.org> (UPN: adestefano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'adestefano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN adestefano@goodwillgoodskills.org) for Robert Johnson"
    }
} else {
    Write-Warning "User rjohnson@goodwillgoodskills.org not found in AD"
}

# --- User: Demetrius Lawrence (dlawrence@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dlawrence@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Demetrius Lawrence"
    }
} else {
    Write-Warning "User dlawrence@goodwillgoodskills.org not found in AD"
}

# --- User: Kelly Brown (kbrown@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kbrown@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Kelly Brown"
    }
} else {
    Write-Warning "User kbrown@goodwillgoodskills.org not found in AD"
}

# --- User: Mark Trew (mtrew@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mtrew@goodwillgoodskills.org'"
if ($user) {
    # Manager: Anne Richards <annerichards@goodwillgoodskills.org> (UPN: annerichards@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'annerichards@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN annerichards@goodwillgoodskills.org) for Mark Trew"
    }
} else {
    Write-Warning "User mtrew@goodwillgoodskills.org not found in AD"
}

# --- User: Scott Buxton (sbuxton@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'sbuxton@goodwillgoodskills.org'"
if ($user) {
    # Manager: Averie Destefano <adestefano@goodwillgoodskills.org> (UPN: adestefano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'adestefano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN adestefano@goodwillgoodskills.org) for Scott Buxton"
    }
} else {
    Write-Warning "User sbuxton@goodwillgoodskills.org not found in AD"
}

# --- User: Willie Dillard (wdillard@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'wdillard@goodwillgoodskills.org'"
if ($user) {
    # Manager: Phil Romano <promano@goodwillgoodskills.org> (UPN: promano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'promano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN promano@goodwillgoodskills.org) for Willie Dillard"
    }
} else {
    Write-Warning "User wdillard@goodwillgoodskills.org not found in AD"
}

# --- User: Amber Beadnell (abeadnell@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'abeadnell@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Amber Beadnell"
    }
} else {
    Write-Warning "User abeadnell@goodwillgoodskills.org not found in AD"
}

# --- User: Mary Smiley (msmiley@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'msmiley@goodwillgoodskills.org'"
if ($user) {
    # Manager: Averie Destefano <adestefano@goodwillgoodskills.org> (UPN: adestefano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'adestefano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN adestefano@goodwillgoodskills.org) for Mary Smiley"
    }
} else {
    Write-Warning "User msmiley@goodwillgoodskills.org not found in AD"
}

# --- User: Ashley Taylor (ataylor@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ataylor@goodwillgoodskills.org'"
if ($user) {
    # Manager: Renee LaFountain <rlafountain@goodwillgoodskills.org> (UPN: rlafountain@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'rlafountain@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN rlafountain@goodwillgoodskills.org) for Ashley Taylor"
    }
} else {
    Write-Warning "User ataylor@goodwillgoodskills.org not found in AD"
}

# --- User: Eileen Healy (ehealy@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ehealy@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Eileen Healy"
    }
} else {
    Write-Warning "User ehealy@goodwillgoodskills.org not found in AD"
}

# --- User: Michele Tokos (mtokos@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mtokos@goodwillgoodskills.org'"
if ($user) {
    # Manager: Marcie Finney <mfinney@goodwillgoodskills.org> (UPN: mfinney@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mfinney@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mfinney@goodwillgoodskills.org) for Michele Tokos"
    }
} else {
    Write-Warning "User mtokos@goodwillgoodskills.org not found in AD"
}

# --- User: Allyson Shawver (ashawver@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ashawver@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Allyson Shawver"
    }
} else {
    Write-Warning "User ashawver@goodwillgoodskills.org not found in AD"
}

# --- User: Jessica Homer (jhomer@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jhomer@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Jessica Homer"
    }
} else {
    Write-Warning "User jhomer@goodwillgoodskills.org not found in AD"
}

# --- User: Alexandra Billings (ashakley@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ashakley@goodwillgoodskills.org'"
if ($user) {
    # Manager: Latoya Currence <lcurrence@goodwillgoodskills.org> (UPN: lcurrence@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'lcurrence@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN lcurrence@goodwillgoodskills.org) for Alexandra Billings"
    }
} else {
    Write-Warning "User ashakley@goodwillgoodskills.org not found in AD"
}

# --- User: Jennifer Rothermel (jrothermel@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jrothermel@goodwillgoodskills.org'"
if ($user) {
    # Manager: Latoya Currence <lcurrence@goodwillgoodskills.org> (UPN: lcurrence@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'lcurrence@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN lcurrence@goodwillgoodskills.org) for Jennifer Rothermel"
    }
} else {
    Write-Warning "User jrothermel@goodwillgoodskills.org not found in AD"
}

# --- User: Kyllan Thomas-Hughes (kthomashughes@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kthomashughes@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Kyllan Thomas-Hughes"
    }
} else {
    Write-Warning "User kthomashughes@goodwillgoodskills.org not found in AD"
}

# --- User: Melanie Anderson (manderson@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'manderson@compassrapecrisis.org'"
if ($user) {
    # Manager: Molly MacMath <director@compassrapecrisis.org> (UPN: director@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'director@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN director@compassrapecrisis.org) for Melanie Anderson"
    }
} else {
    Write-Warning "User manderson@compassrapecrisis.org not found in AD"
}

# --- User: Marcy Thompson (mthompson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mthompson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Marcy Thompson"
    }
} else {
    Write-Warning "User mthompson@goodwillgoodskills.org not found in AD"
}

# --- User: Colleen Porter (cporter@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cporter@goodwillgoodskills.org'"
if ($user) {
    # Manager: Diane Pilati <DPILATI@goodwillgoodskills.org> (UPN: DPILATI@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'DPILATI@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN DPILATI@goodwillgoodskills.org) for Colleen Porter"
    }
} else {
    Write-Warning "User cporter@goodwillgoodskills.org not found in AD"
}

# --- User: Nolan Vandervaart (nvandeervaart2@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'nvandeervaart2@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Nolan Vandervaart"
    }
} else {
    Write-Warning "User nvandeervaart2@goodwillgoodskills.org not found in AD"
}

# --- User: Grace Worley (jworley@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jworley@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Grace Worley"
    }
} else {
    Write-Warning "User jworley@goodwillgoodskills.org not found in AD"
}

# --- User: Bobby Greenwald (bgreenwald@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'bgreenwald@goodwillgoodskills.org'"
if ($user) {
    # Manager: Michael Murphy <mmurphy@goodwillgoodskills.org> (UPN: mmurphy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mmurphy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mmurphy@goodwillgoodskills.org) for Bobby Greenwald"
    }
} else {
    Write-Warning "User bgreenwald@goodwillgoodskills.org not found in AD"
}

# --- User: Emily Hiner (ehiner@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ehiner@compassrapecrisis.org'"
if ($user) {
    # Manager: Molly MacMath <director@compassrapecrisis.org> (UPN: director@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'director@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN director@compassrapecrisis.org) for Emily Hiner"
    }
} else {
    Write-Warning "User ehiner@compassrapecrisis.org not found in AD"
}

# --- User: Jodie Johnson (jjohnson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jjohnson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Jodie Johnson"
    }
} else {
    Write-Warning "User jjohnson@goodwillgoodskills.org not found in AD"
}

# --- User: Diane Pilati (DPILATI@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'DPILATI@goodwillgoodskills.org'"
if ($user) {
    # Manager: Anne Richards <annerichards@goodwillgoodskills.org> (UPN: annerichards@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'annerichards@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN annerichards@goodwillgoodskills.org) for Diane Pilati"
    }
} else {
    Write-Warning "User DPILATI@goodwillgoodskills.org not found in AD"
}

# --- User: Roy Garrett (rgarrett@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'rgarrett@goodwillgoodskills.org'"
if ($user) {
    # Manager: Nolberto Giraldo <ngiraldo@goodwillgoodskills.org> (UPN: ngiraldo@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'ngiraldo@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN ngiraldo@goodwillgoodskills.org) for Roy Garrett"
    }
} else {
    Write-Warning "User rgarrett@goodwillgoodskills.org not found in AD"
}

# --- User: Nolberto Giraldo (ngiraldo@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ngiraldo@goodwillgoodskills.org'"
if ($user) {
    # Manager: Kevin Akans <kakans@goodwillgoodskills.org> (UPN: kakans@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'kakans@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN kakans@goodwillgoodskills.org) for Nolberto Giraldo"
    }
} else {
    Write-Warning "User ngiraldo@goodwillgoodskills.org not found in AD"
}

# --- User: Carla LaFountain (rlafountain@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'rlafountain@goodwillgoodskills.org'"
if ($user) {
    # Manager: Latoya Currence <lcurrence@goodwillgoodskills.org> (UPN: lcurrence@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'lcurrence@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN lcurrence@goodwillgoodskills.org) for Carla LaFountain"
    }
} else {
    Write-Warning "User rlafountain@goodwillgoodskills.org not found in AD"
}

# --- User: Michael Cox (mcox@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mcox@goodwillgoodskills.org'"
if ($user) {
    # Manager: Nolberto Giraldo <ngiraldo@goodwillgoodskills.org> (UPN: ngiraldo@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'ngiraldo@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN ngiraldo@goodwillgoodskills.org) for Michael Cox"
    }
} else {
    Write-Warning "User mcox@goodwillgoodskills.org not found in AD"
}

# --- User: Shaunaugh Turner (sturner@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'sturner@compassrapecrisis.org'"
if ($user) {
    # Manager: Molly MacMath <director@compassrapecrisis.org> (UPN: director@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'director@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN director@compassrapecrisis.org) for Shaunaugh Turner"
    }
} else {
    Write-Warning "User sturner@compassrapecrisis.org not found in AD"
}

# --- User: Tori Hall (thall@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'thall@goodwillgoodskills.org'"
if ($user) {
    # Manager: Latoya Currence <lcurrence@goodwillgoodskills.org> (UPN: lcurrence@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'lcurrence@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN lcurrence@goodwillgoodskills.org) for Tori Hall"
    }
} else {
    Write-Warning "User thall@goodwillgoodskills.org not found in AD"
}

# --- User: Teresa Debarlaben (tdebarlaben@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'tdebarlaben@goodwillgoodskills.org'"
if ($user) {
    # Manager: Christopher Ady <cady@goodwillgoodskills.org> (UPN: cady@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cady@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cady@goodwillgoodskills.org) for Teresa Debarlaben"
    }
} else {
    Write-Warning "User tdebarlaben@goodwillgoodskills.org not found in AD"
}

# --- User: Nichole Samsa (nsamsa@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'nsamsa@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Nichole Samsa"
    }
} else {
    Write-Warning "User nsamsa@goodwillgoodskills.org not found in AD"
}

# --- User: Jacqueline Kienzle (jkienzle@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jkienzle@goodwillgoodskills.org'"
if ($user) {
    # Manager: Latoya Currence <lcurrence@goodwillgoodskills.org> (UPN: lcurrence@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'lcurrence@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN lcurrence@goodwillgoodskills.org) for Jacqueline Kienzle"
    }
} else {
    Write-Warning "User jkienzle@goodwillgoodskills.org not found in AD"
}

# --- User: Joshua Montgomery (JMontgomery@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'JMontgomery@goodwillgoodskills.org'"
if ($user) {
    # Manager: Phil Romano <promano@goodwillgoodskills.org> (UPN: promano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'promano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN promano@goodwillgoodskills.org) for Joshua Montgomery"
    }
} else {
    Write-Warning "User JMontgomery@goodwillgoodskills.org not found in AD"
}

# --- User: David Gongo (dgongo@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dgongo@goodwillgoodskills.org'"
if ($user) {
    # Manager: Nolberto Giraldo <ngiraldo@goodwillgoodskills.org> (UPN: ngiraldo@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'ngiraldo@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN ngiraldo@goodwillgoodskills.org) for David Gongo"
    }
} else {
    Write-Warning "User dgongo@goodwillgoodskills.org not found in AD"
}

# --- User: Nicole Steele (NSteele@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'NSteele@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Nicole Steele"
    }
} else {
    Write-Warning "User NSteele@goodwillgoodskills.org not found in AD"
}

# --- User: Alex Siracki (asiracki@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'asiracki@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Alex Siracki"
    }
} else {
    Write-Warning "User asiracki@goodwillgoodskills.org not found in AD"
}

# --- User: Laura Reynolds (lreynolds@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'lreynolds@goodwillgoodskills.org'"
if ($user) {
    # Manager: Meghan Freyburger <mfreyburger@goodwillgoodskills.org> (UPN: mfreyburger@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mfreyburger@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mfreyburger@goodwillgoodskills.org) for Laura Reynolds"
    }
} else {
    Write-Warning "User lreynolds@goodwillgoodskills.org not found in AD"
}

# --- User: Brianna Yacono (byacono@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'byacono@compassrapecrisis.org'"
if ($user) {
    # Manager: Melanie Anderson <manderson@compassrapecrisis.org> (UPN: manderson@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'manderson@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN manderson@compassrapecrisis.org) for Brianna Yacono"
    }
} else {
    Write-Warning "User byacono@compassrapecrisis.org not found in AD"
}

# --- User: Kelley Beam (kbeam@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kbeam@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Kelley Beam"
    }
} else {
    Write-Warning "User kbeam@goodwillgoodskills.org not found in AD"
}

# --- User: Moira Hill (mhill@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mhill@compassrapecrisis.org'"
if ($user) {
    # Manager: Melanie Anderson <manderson@compassrapecrisis.org> (UPN: manderson@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'manderson@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN manderson@compassrapecrisis.org) for Moira Hill"
    }
} else {
    Write-Warning "User mhill@compassrapecrisis.org not found in AD"
}

# --- User: Traci Alcorn (talcorn@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'talcorn@goodwillgoodskills.org'"
if ($user) {
    # Manager: Michael Murphy <mmurphy@goodwillgoodskills.org> (UPN: mmurphy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mmurphy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mmurphy@goodwillgoodskills.org) for Traci Alcorn"
    }
} else {
    Write-Warning "User talcorn@goodwillgoodskills.org not found in AD"
}

# --- User: Erin Peltz (epeltz@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'epeltz@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jennifer Fire <jfire@goodwillgoodskills.org> (UPN: jfire@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jfire@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jfire@goodwillgoodskills.org) for Erin Peltz"
    }
} else {
    Write-Warning "User epeltz@goodwillgoodskills.org not found in AD"
}

# --- User: Nicholas Fowler (nfowler@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'nfowler@goodwillgoodskills.org'"
if ($user) {
    # Manager: Christian Williams <cwilliams@goodwillgoodskills.org> (UPN: cwilliams@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwilliams@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwilliams@goodwillgoodskills.org) for Nicholas Fowler"
    }
} else {
    Write-Warning "User nfowler@goodwillgoodskills.org not found in AD"
}

# --- User: Vincent Getz (vgetz@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'vgetz@goodwillgoodskills.org'"
if ($user) {
    # Manager: Amy Morgan <amymorgan@goodwillgoodskills.org> (UPN: amymorgan@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'amymorgan@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN amymorgan@goodwillgoodskills.org) for Vincent Getz"
    }
} else {
    Write-Warning "User vgetz@goodwillgoodskills.org not found in AD"
}

# --- User: Deborah Hall (dhall@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dhall@goodwillgoodskills.org'"
if ($user) {
    # Manager: Colleen Porter <cporter@goodwillgoodskills.org> (UPN: cporter@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cporter@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cporter@goodwillgoodskills.org) for Deborah Hall"
    }
} else {
    Write-Warning "User dhall@goodwillgoodskills.org not found in AD"
}

# --- User: Dre'ane Travis Jr (dtravis@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dtravis@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Dre'ane Travis Jr"
    }
} else {
    Write-Warning "User dtravis@goodwillgoodskills.org not found in AD"
}

# --- User: Mark McMasters (mmcmasters@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mmcmasters@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Mark McMasters"
    }
} else {
    Write-Warning "User mmcmasters@goodwillgoodskills.org not found in AD"
}

# --- User: Candy Roesler (croesler@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'croesler@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Candy Roesler"
    }
} else {
    Write-Warning "User croesler@goodwillgoodskills.org not found in AD"
}

# --- User: Ebony McGill (emcgill@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'emcgill@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Ebony McGill"
    }
} else {
    Write-Warning "User emcgill@goodwillgoodskills.org not found in AD"
}

# --- User: Glenn Stoler (gstoler@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'gstoler@goodwillgoodskills.org'"
if ($user) {
    # Manager: Michael Murphy <mmurphy@goodwillgoodskills.org> (UPN: mmurphy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mmurphy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mmurphy@goodwillgoodskills.org) for Glenn Stoler"
    }
} else {
    Write-Warning "User gstoler@goodwillgoodskills.org not found in AD"
}

# --- User: Sharon Pettus (spettus@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'spettus@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Sharon Pettus"
    }
} else {
    Write-Warning "User spettus@goodwillgoodskills.org not found in AD"
}

# --- User: Gabrielle Gayheart (ggayheart@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ggayheart@compassrapecrisis.org'"
if ($user) {
    # Manager: Melanie Anderson <manderson@compassrapecrisis.org> (UPN: manderson@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'manderson@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN manderson@compassrapecrisis.org) for Gabrielle Gayheart"
    }
} else {
    Write-Warning "User ggayheart@compassrapecrisis.org not found in AD"
}

# --- User: Marguerite Hoover (mhoover@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mhoover@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Marguerite Hoover"
    }
} else {
    Write-Warning "User mhoover@goodwillgoodskills.org not found in AD"
}

# --- User: Lisa Green (lgreen@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'lgreen@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Lisa Green"
    }
} else {
    Write-Warning "User lgreen@goodwillgoodskills.org not found in AD"
}

# --- User: Taylar Vance (tvance@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'tvance@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Taylar Vance"
    }
} else {
    Write-Warning "User tvance@goodwillgoodskills.org not found in AD"
}

# --- User: Alexandria Beatty (aforemaster@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'aforemaster@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Alexandria Beatty"
    }
} else {
    Write-Warning "User aforemaster@goodwillgoodskills.org not found in AD"
}

# --- User: Breanna Antoniades (bantoniades@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'bantoniades@goodwillgoodskills.org'"
if ($user) {
    # Manager: Latoya Currence <lcurrence@goodwillgoodskills.org> (UPN: lcurrence@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'lcurrence@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN lcurrence@goodwillgoodskills.org) for Breanna Antoniades"
    }
} else {
    Write-Warning "User bantoniades@goodwillgoodskills.org not found in AD"
}

# --- User: Kayla Stover (kstover@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kstover@compassrapecrisis.org'"
if ($user) {
    # Manager: Molly MacMath <director@compassrapecrisis.org> (UPN: director@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'director@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN director@compassrapecrisis.org) for Kayla Stover"
    }
} else {
    Write-Warning "User kstover@compassrapecrisis.org not found in AD"
}

# --- User: Wendy Bullock (wbullock@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'wbullock@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Wendy Bullock"
    }
} else {
    Write-Warning "User wbullock@goodwillgoodskills.org not found in AD"
}

# --- User: Kelsey Davis (kdavis@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kdavis@goodwillgoodskills.org'"
if ($user) {
    # Manager: Diane Pilati <DPILATI@goodwillgoodskills.org> (UPN: DPILATI@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'DPILATI@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN DPILATI@goodwillgoodskills.org) for Kelsey Davis"
    }
} else {
    Write-Warning "User kdavis@goodwillgoodskills.org not found in AD"
}

# --- User: Victoria Storsin (vstorsin@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'vstorsin@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Victoria Storsin"
    }
} else {
    Write-Warning "User vstorsin@goodwillgoodskills.org not found in AD"
}

# --- User: Darilyn Howell (dhowell@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dhowell@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Darilyn Howell"
    }
} else {
    Write-Warning "User dhowell@goodwillgoodskills.org not found in AD"
}

# --- User: Brian Tepsic (btepsic@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'btepsic@goodwillgoodskills.org'"
if ($user) {
    # Manager: Michael Cox <mcox@goodwillgoodskills.org> (UPN: mcox@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mcox@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mcox@goodwillgoodskills.org) for Brian Tepsic"
    }
} else {
    Write-Warning "User btepsic@goodwillgoodskills.org not found in AD"
}

# --- User: Danielle Nicholson (dnicholson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'dnicholson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Danielle Nicholson"
    }
} else {
    Write-Warning "User dnicholson@goodwillgoodskills.org not found in AD"
}

# --- User: Cassandra Lopiccolo (clopiccolo@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'clopiccolo@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Cassandra Lopiccolo"
    }
} else {
    Write-Warning "User clopiccolo@goodwillgoodskills.org not found in AD"
}

# --- User: Aaron Hooper (ahooper@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ahooper@goodwillgoodskills.org'"
if ($user) {
    # Manager: Amy Morgan <amymorgan@goodwillgoodskills.org> (UPN: amymorgan@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'amymorgan@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN amymorgan@goodwillgoodskills.org) for Aaron Hooper"
    }
} else {
    Write-Warning "User ahooper@goodwillgoodskills.org not found in AD"
}

# --- User: Rebecca Preston (rpreston@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'rpreston@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Rebecca Preston"
    }
} else {
    Write-Warning "User rpreston@goodwillgoodskills.org not found in AD"
}

# --- User: Alexandra Yoskey (adowell@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'adowell@goodwillgoodskills.org'"
if ($user) {
    # Manager: Diane Pilati <DPILATI@goodwillgoodskills.org> (UPN: DPILATI@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'DPILATI@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN DPILATI@goodwillgoodskills.org) for Alexandra Yoskey"
    }
} else {
    Write-Warning "User adowell@goodwillgoodskills.org not found in AD"
}

# --- User: Gina Shaffer (gshaffer@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'gshaffer@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Gina Shaffer"
    }
} else {
    Write-Warning "User gshaffer@goodwillgoodskills.org not found in AD"
}

# --- User: Courtney Robinson (crobinson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'crobinson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Courtney Robinson"
    }
} else {
    Write-Warning "User crobinson@goodwillgoodskills.org not found in AD"
}

# --- User: Florence Hallett (fhallett@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'fhallett@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jennifer Fire <jfire@goodwillgoodskills.org> (UPN: jfire@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jfire@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jfire@goodwillgoodskills.org) for Florence Hallett"
    }
} else {
    Write-Warning "User fhallett@goodwillgoodskills.org not found in AD"
}

# --- User: Sloan Kyler (skyler@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'skyler@compassrapecrisis.org'"
if ($user) {
    # Manager: Kayla Stover <kstover@compassrapecrisis.org> (UPN: kstover@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'kstover@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN kstover@compassrapecrisis.org) for Sloan Kyler"
    }
} else {
    Write-Warning "User skyler@compassrapecrisis.org not found in AD"
}

# --- User: Kimberly Striker (kstriker@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kstriker@compassrapecrisis.org'"
if ($user) {
    # Manager: Melanie Anderson <manderson@compassrapecrisis.org> (UPN: manderson@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'manderson@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN manderson@compassrapecrisis.org) for Kimberly Striker"
    }
} else {
    Write-Warning "User kstriker@compassrapecrisis.org not found in AD"
}

# --- User: Holly Keller (hkeller@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'hkeller@compassrapecrisis.org'"
if ($user) {
    # Manager: Kayla Stover <kstover@compassrapecrisis.org> (UPN: kstover@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'kstover@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN kstover@compassrapecrisis.org) for Holly Keller"
    }
} else {
    Write-Warning "User hkeller@compassrapecrisis.org not found in AD"
}

# --- User: Ondrea Petite (opetite@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'opetite@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Ondrea Petite"
    }
} else {
    Write-Warning "User opetite@goodwillgoodskills.org not found in AD"
}

# --- User: Kevin Akans (kakans@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kakans@goodwillgoodskills.org'"
if ($user) {
    # Manager: Anne Richards <annerichards@goodwillgoodskills.org> (UPN: annerichards@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'annerichards@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN annerichards@goodwillgoodskills.org) for Kevin Akans"
    }
} else {
    Write-Warning "User kakans@goodwillgoodskills.org not found in AD"
}

# --- User: Patricia Hairston (phairston@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'phairston@goodwillgoodskills.org'"
if ($user) {
    # Manager: Averie Destefano <adestefano@goodwillgoodskills.org> (UPN: adestefano@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'adestefano@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN adestefano@goodwillgoodskills.org) for Patricia Hairston"
    }
} else {
    Write-Warning "User phairston@goodwillgoodskills.org not found in AD"
}

# --- User: Cora Dean (cdean@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cdean@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Cora Dean"
    }
} else {
    Write-Warning "User cdean@goodwillgoodskills.org not found in AD"
}

# --- User: Shiann Cook (scook@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'scook@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Shiann Cook"
    }
} else {
    Write-Warning "User scook@goodwillgoodskills.org not found in AD"
}

# --- User: Riley Elliott (relliott@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'relliott@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Riley Elliott"
    }
} else {
    Write-Warning "User relliott@goodwillgoodskills.org not found in AD"
}

# --- User: Chanelle Austin (caustin@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'caustin@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Chanelle Austin"
    }
} else {
    Write-Warning "User caustin@goodwillgoodskills.org not found in AD"
}

# --- User: Sarah Smith (ssmith@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ssmith@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Sarah Smith"
    }
} else {
    Write-Warning "User ssmith@goodwillgoodskills.org not found in AD"
}

# --- User: Elyssa Linderman (elinderman@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'elinderman@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Elyssa Linderman"
    }
} else {
    Write-Warning "User elinderman@goodwillgoodskills.org not found in AD"
}

# --- User: Norma Winkhart (nwinkhart@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'nwinkhart@goodwillgoodskills.org'"
if ($user) {
    # Manager: Christian Williams <cwilliams@goodwillgoodskills.org> (UPN: cwilliams@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwilliams@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwilliams@goodwillgoodskills.org) for Norma Winkhart"
    }
} else {
    Write-Warning "User nwinkhart@goodwillgoodskills.org not found in AD"
}

# --- User: Micheal Clayton (mclayton@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mclayton@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Micheal Clayton"
    }
} else {
    Write-Warning "User mclayton@goodwillgoodskills.org not found in AD"
}

# --- User: Jacob Lindberg (jlindberg@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jlindberg@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Jacob Lindberg"
    }
} else {
    Write-Warning "User jlindberg@goodwillgoodskills.org not found in AD"
}

# --- User: Antonio Bouldin (abouldin@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'abouldin@goodwillgoodskills.org'"
if ($user) {
    # Manager: Nolberto Giraldo <ngiraldo@goodwillgoodskills.org> (UPN: ngiraldo@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'ngiraldo@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN ngiraldo@goodwillgoodskills.org) for Antonio Bouldin"
    }
} else {
    Write-Warning "User abouldin@goodwillgoodskills.org not found in AD"
}

# --- User: Nicholas Vincent (nvincent@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'nvincent@goodwillgoodskills.org'"
if ($user) {
    # Manager: Christian Williams <cwilliams@goodwillgoodskills.org> (UPN: cwilliams@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwilliams@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwilliams@goodwillgoodskills.org) for Nicholas Vincent"
    }
} else {
    Write-Warning "User nvincent@goodwillgoodskills.org not found in AD"
}

# --- User: Christian Graber (cgraber@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cgraber@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Christian Graber"
    }
} else {
    Write-Warning "User cgraber@goodwillgoodskills.org not found in AD"
}

# --- User: Casey Hall (chall@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'chall@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Casey Hall"
    }
} else {
    Write-Warning "User chall@goodwillgoodskills.org not found in AD"
}

# --- User: Sidney Mikhail (smikhail@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'smikhail@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Sidney Mikhail"
    }
} else {
    Write-Warning "User smikhail@goodwillgoodskills.org not found in AD"
}

# --- User: Victoria Herrick (vherrick@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'vherrick@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Victoria Herrick"
    }
} else {
    Write-Warning "User vherrick@goodwillgoodskills.org not found in AD"
}

# --- User: Ryan Shimko (rshimko@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'rshimko@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Ryan Shimko"
    }
} else {
    Write-Warning "User rshimko@goodwillgoodskills.org not found in AD"
}

# --- User: Tracy Figurella (tfigurella@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'tfigurella@goodwillgoodskills.org'"
if ($user) {
    # Manager: Marcie Finney <mfinney@goodwillgoodskills.org> (UPN: mfinney@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mfinney@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mfinney@goodwillgoodskills.org) for Tracy Figurella"
    }
} else {
    Write-Warning "User tfigurella@goodwillgoodskills.org not found in AD"
}

# --- User: Jordyn Wheaton (jwheaton@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jwheaton@goodwillgoodskills.org'"
if ($user) {
    # Manager: Tracy Figurella <tfigurella@goodwillgoodskills.org> (UPN: tfigurella@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'tfigurella@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN tfigurella@goodwillgoodskills.org) for Jordyn Wheaton"
    }
} else {
    Write-Warning "User jwheaton@goodwillgoodskills.org not found in AD"
}

# --- User: Michelle Anderson (michelleanderson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'michelleanderson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Cynthia Woodall <cwoodall@goodwillgoodskills.org> (UPN: cwoodall@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwoodall@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwoodall@goodwillgoodskills.org) for Michelle Anderson"
    }
} else {
    Write-Warning "User michelleanderson@goodwillgoodskills.org not found in AD"
}

# --- User: Celeste DeHoff (cdehoff@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'cdehoff@compassrapecrisis.org'"
if ($user) {
    # Manager: Molly MacMath <director@compassrapecrisis.org> (UPN: director@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'director@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN director@compassrapecrisis.org) for Celeste DeHoff"
    }
} else {
    Write-Warning "User cdehoff@compassrapecrisis.org not found in AD"
}

# --- User: Kelly Standish (kstandish@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'kstandish@goodwillgoodskills.org'"
if ($user) {
    # Manager: Anne Richards <annerichards@goodwillgoodskills.org> (UPN: annerichards@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'annerichards@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN annerichards@goodwillgoodskills.org) for Kelly Standish"
    }
} else {
    Write-Warning "User kstandish@goodwillgoodskills.org not found in AD"
}

# --- User: Niesha Davis (nieshadavis@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'nieshadavis@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Niesha Davis"
    }
} else {
    Write-Warning "User nieshadavis@goodwillgoodskills.org not found in AD"
}

# --- User: Steven Okey (sokey@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'sokey@goodwillgoodskills.org'"
if ($user) {
    # Manager: Ellen McCarthy <emccarthy@goodwillgoodskills.org> (UPN: emccarthy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'emccarthy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN emccarthy@goodwillgoodskills.org) for Steven Okey"
    }
} else {
    Write-Warning "User sokey@goodwillgoodskills.org not found in AD"
}

# --- User: Christopher Kopp (ckopp@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ckopp@goodwillgoodskills.org'"
if ($user) {
    # Manager: Christian Williams <cwilliams@goodwillgoodskills.org> (UPN: cwilliams@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'cwilliams@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN cwilliams@goodwillgoodskills.org) for Christopher Kopp"
    }
} else {
    Write-Warning "User ckopp@goodwillgoodskills.org not found in AD"
}

# --- User: Gerald Duncan (gduncan@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'gduncan@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Gerald Duncan"
    }
} else {
    Write-Warning "User gduncan@goodwillgoodskills.org not found in AD"
}

# --- User: Latoya Currence (lcurrence@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'lcurrence@goodwillgoodskills.org'"
if ($user) {
    # Manager: Anne Richards <annerichards@goodwillgoodskills.org> (UPN: annerichards@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'annerichards@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN annerichards@goodwillgoodskills.org) for Latoya Currence"
    }
} else {
    Write-Warning "User lcurrence@goodwillgoodskills.org not found in AD"
}

# --- User: Ronald Pike (RPike@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'RPike@goodwillgoodskills.org'"
if ($user) {
    # Manager: Michael Murphy <mmurphy@goodwillgoodskills.org> (UPN: mmurphy@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mmurphy@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mmurphy@goodwillgoodskills.org) for Ronald Pike"
    }
} else {
    Write-Warning "User RPike@goodwillgoodskills.org not found in AD"
}

# --- User: Justin Johnson (justinjohnson@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'justinjohnson@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Justin Johnson"
    }
} else {
    Write-Warning "User justinjohnson@goodwillgoodskills.org not found in AD"
}

# --- User: Tanisha Haynes (thaynes@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'thaynes@goodwillgoodskills.org'"
if ($user) {
    # Manager: Megan Clow <mclow@goodwillgoodskills.org> (UPN: mclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'mclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN mclow@goodwillgoodskills.org) for Tanisha Haynes"
    }
} else {
    Write-Warning "User thaynes@goodwillgoodskills.org not found in AD"
}

# --- User: Kegan Steckel (Ksteckel@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'Ksteckel@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Kegan Steckel"
    }
} else {
    Write-Warning "User Ksteckel@goodwillgoodskills.org not found in AD"
}

# --- User: Janet Eagon (jeagon@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'jeagon@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jennifer Fire <jfire@goodwillgoodskills.org> (UPN: jfire@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jfire@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jfire@goodwillgoodskills.org) for Janet Eagon"
    }
} else {
    Write-Warning "User jeagon@goodwillgoodskills.org not found in AD"
}

# --- User: Tiffany Horn (thorn@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'thorn@goodwillgoodskills.org'"
if ($user) {
    # Manager: Katie Gauze <agauze@goodwillgoodskills.org> (UPN: agauze@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'agauze@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN agauze@goodwillgoodskills.org) for Tiffany Horn"
    }
} else {
    Write-Warning "User thorn@goodwillgoodskills.org not found in AD"
}

# --- User: Hannah Griffin (hgriffin@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'hgriffin@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jennifer Fire <jfire@goodwillgoodskills.org> (UPN: jfire@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jfire@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jfire@goodwillgoodskills.org) for Hannah Griffin"
    }
} else {
    Write-Warning "User hgriffin@goodwillgoodskills.org not found in AD"
}

# --- User: Isaiah Humphries (ihumphries@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'ihumphries@goodwillgoodskills.org'"
if ($user) {
    # Manager: Jami George <jgeorge@goodwillgoodskills.org> (UPN: jgeorge@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'jgeorge@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN jgeorge@goodwillgoodskills.org) for Isaiah Humphries"
    }
} else {
    Write-Warning "User ihumphries@goodwillgoodskills.org not found in AD"
}

# --- User: Michele Reich (mreich@compassrapecrisis.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'mreich@compassrapecrisis.org'"
if ($user) {
    # Manager: Melanie Anderson <manderson@compassrapecrisis.org> (UPN: manderson@compassrapecrisis.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'manderson@compassrapecrisis.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN manderson@compassrapecrisis.org) for Michele Reich"
    }
} else {
    Write-Warning "User mreich@compassrapecrisis.org not found in AD"
}

# --- User: Samantha Barnett (SamanthaBarnett@goodwillgoodskills.org) ---
$user = Get-ADUser -Filter "UserPrincipalName -eq 'SamanthaBarnett@goodwillgoodskills.org'"
if ($user) {
    # Manager: Brandon Clow <bclow@goodwillgoodskills.org> (UPN: bclow@goodwillgoodskills.org)
    $mgr = Get-ADUser -Filter "UserPrincipalName -eq 'bclow@goodwillgoodskills.org'"
    if ($mgr) {
        Set-ADUser $user -Manager $mgr.DistinguishedName
    } else {
        Write-Warning "Could not resolve manager (UPN bclow@goodwillgoodskills.org) for Samantha Barnett"
    }
} else {
    Write-Warning "User SamanthaBarnett@goodwillgoodskills.org not found in AD"
}
